WebsiteAssignmentNew/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsiteAssignmentNew.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebsiteAssignmentNew/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsiteAssignmentNew.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebsiteAssignmentNew/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteAssignmentNew.Models;

namespace WebsiteAssignmentNew.Controllers
{
    public class UserController : Controller
    {
        DAO dao = new DAO();
        // GET: User
        public ActionResult Index()
        {
            return View("Register");
        }

        [HttpPost]

        public ActionResult Register(UserModel user)
        {
            int count = 0;
            if (ModelState.IsValid)
            {
                count = dao.Insert(user);
                if (count == 1)
                {
                    ViewBag.Status = "New user created";
                }
                else
                {
                    ViewBag.Status = "Error! " + dao.message;
                }
                return View("Status");
            }
            return View(user);
        }
    }
}

WebsiteAssignmentNew/Views/Shared/LoginRegister.cshtml
@Html.ActionLink("Register", "Index", "User", null, new { @class = "register" })
@Html.ActionLink("Login /", "Login", "User", null, new { @class = "register" })

WebsiteAssignmentNew/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="BadCat Records release groundbreaking new music from Irish and international artists">
    <meta name="keywords" content="BadCat, Bad, Cat, Records, Record Label, Dublin, Ireland, Music, Electronic, Dance, Remix, Electronica, Vinyl, Digital, CD, Digital Download, Watch and Listen, Listen ">
    <meta name="viewport" content="width= device-width, initial scale=1.0">
    <meta name="author" content="Aodh O’Sullivan, Graham Lee, Ultan Gannon">

    <style type="text/css" media="screen"></style>
    <title>BadCat Records @ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/styles.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script language="javascript" src="~/Scripts/fade.js"></script>



</head>


<body class="col-md-12">
    <div id="wrapper" >
        <header>
            <div id="headimg" class="col-md-12">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <!--<img id="logo" alt="badcattextlogo" src="~/Content/Images/croppedLogo.png" class="right" />-->

                            <img id="logoText" alt="badcatlogotext" src="~/Content/Images/textLogo.png" class="rounded float-left" />
                        </div>
                        <div class="col-md-6">
                            <img id="eyes" alt="eyesLogo" src="~/Content/Images/eyes2.png" class="rounded float-right" />
                            <!--<h2><em>BadCat Records</em></h2>-->
                        </div>
                        @*<div class="col-md-12">
                            <img src="~/Content/MiscImg/textureRed.jpg" />
                        </div>*@
                    </div>
                </div>
            </div>
        </header>




        <nav>
            <ul class="col-md-12">
                @*<div class="col-md-8">*@

                    <li>
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Tracks", "Index", "Tracks")
                    </li>
                    <li>
                        @Html.ActionLink("Artist", "Index", "Artist")
                    </li>
                    <li>
                        @Html.ActionLink("Shop", "Index", "Shop")
                    </li>
                    <li>
                        @Html.ActionLink("About Us", "Index", "About")
                    </li>
                    <li>
                        @Html.ActionLink("Contact Us", "Index", "Contact")
                    </li>
                @*</div>
                <div class="col-md-4">*@
                    <li id="logIn">
                        @*@{Html.RenderPartial("LoginRegister"); }*@
                        @RenderPage("LoginRegister.cshtml")
                        @RenderSection("Logged", false)
                    </li>
                @*</div>*@
    </ul>

    </nav>
    <main>
         @RenderBody()

    </main>
    <footer>


        <p>
            <a id="footLink" href="#">Back to top</a>
        </p>
            <p>
                <a href="http:\\www.facebook.com" target="_blank"><img src="~/Content/MiscImg/facebookBlack.png" width="30" /></a>
                <a href="http:\\www.twitter.com" target="_blank"><img src="~/Content/MiscImg/twitterBlack.png" width="30" /></a>
                <a href="mailto:info@badcatrecords.com?subject=info" target="_blank"><img src="~/Content/MiscImg/mailBlack.png" width="30" /></a>
                <a href="http:\\www.snapchat.com" target="_blank"><img src="~/Content/MiscImg/snapchatBlack.png" width="30" /></a>
                <a href="http:\\www.youtube.com" target="_blank"><img src="~/Content/MiscImg/youtubeBlack.png" width="30" /></a>

            </p>
        @*<p id="footLogo">

                <img id="footLogoL" src="~/Content/Images/logoSmall.png" />
                <img id="footLogoR" src="~/Content/Images/logoSmall.png" />
        </p>*@

        <h5>
            BadCat Records &copy; @DateTime.Now.Year &nbsp;
        </h5>

    </footer>
    </div>
</body>
</html>